### PR TITLE
Chore/waypoint altitude

### LINKED ISSUE #176: BUG: THE PLANE WILL NOSEDIVE INTO THE GROUND 100% GUARANTEED!
A video demonstration:

[Screencast from 05-03-2024 06:03:41 PM.webm](https://github.com/tritonuas/obcpp/assets/22576354/2ba0409d-56e6-4a4e-a177-92c56125ec05)

The root cause:

Screenshot from 2024-05-03 18-01-03

It just looks like we're not setting altitudes correctly in static pathing, so that should be an easy fix.

(to be clear, I think this is very funny, and a very good example of why SITL testing is important! How did all of us not notice this!)

### PR DESCRIPTION
**Pull request by AskewParity**
closes #176

# Path Fetching

This code's main purpose was to add altitude to the path - which it has done, but by offloading path fetching from the `RRTTree` to `RRT` static pathing.

## Justification

The path planning itself is altitude agnostic, so I've kept it that way and instead added altitude to be an extra function when a waypoint has been achieved.

This also changed the path planning to have "almost" all functionality happen between waypoints, and does not depend on the state of the tree beyond the current waypoint (the past).

## Concerns

Need to check if the flight path includes the waypoint itself, and not just the points between them.

### CODE REVIEW

**Comment by AskewParity** [comment]
DONT MERGE, path doesn't include waypoints

**Comment by Tyler-Lentz** [comment]
> DONT MERGE, path doesn't include waypoints

image

**Comment by AskewParity** [comment]
Waypoints are back, but I'm still not sure if this is the correct list of points.

**Comment by Tyler-Lentz** [comment]
> Waypoints are back, but I'm still not sure if this is the correct list of points.
If you want to get the OBC <--> GCS <--> SITL integration running on your localhost it might make some of the testing easier, and this is something we're going to need to do eventaully. If you're able to come down to the lab we could get that set up. I'll be here for the next 3.5 hours since Im just working on various things until the town hall

**Comment by AskewParity** [comment]
The new path doesn't include the starting point, but thats probably a good thing anyways.

I'll merge the PR into main.

**Pull request merged**
